export const ACTIVITY_ACTIONS = [
  'auth.logged_in',
  'product.created',
  'product.updated',
  'product.deleted',
  'product.barcode_set',
  'product.image_set',
  'pricing.updated',
  'stock.adjusted',
  'sale.recorded',
  'document.fiscal_receipt',
  'bill.added',
  'bill.updated',
  'bill.paid',
  'bill.payment_voided',
  'bill.voided',
  'category.created',
  'category.updated',
  'category.deleted',
  'user.created',
  'user.invited',
  'user.updated',
  'user.deleted',
  'return.requested',
  'return.approved',
  'return.rejected',
  'write_off.requested',
  'write_off.approved',
  'write_off.rejected',
  'count.started',
  'count.submitted',
  'count.cancelled',
  'count.line_approved',
  'count.line_rejected',
  'settings.updated',
  'shop.wiped',
  'promotion.created',
  'promotion.ended',
  'carwash.created',
  'carwash.updated',
  'carwash.archived',
  'carwash.restored',
  'carwash.recorded',
  'carwash.removed',
  'cash.counted',
  'cash.checked',
  'expense.added',
  'expense.removed',
  'expense.repeat_stopped',
  'expense.none_marked',
  'expense.none_cleared',
  'customer.created',
  'customer.updated',
  'customer.archived',
  'tab.paid',
  'supplier.created',
  'supplier.updated',
  'supplier.removed',
  'order.created',
  'order.received',
  'order.cancelled',
  'expiry.added',
  'expiry.cleared',
  'undo.applied',
  'undo.restored',
] as const;

export type ActivityAction = (typeof ACTIVITY_ACTIONS)[number];

export const ACTIVITY_ENTITY_TYPES = ['product', 'category', 'user', 'sale', 'return', 'write_off', 'stock_count', 'settings', 'promotion', 'carwash', 'cash_count', 'expense', 'customer', 'supplier', 'order', 'document', 'bill', 'activity'] as const;
export type ActivityEntityType = (typeof ACTIVITY_ENTITY_TYPES)[number];
